### ISSUE TITLE
Json Get Request

### ISSUE THREAD

**Issue by johnjake** [royd/Xamarin.Android.Volley#1]
Hey can you give a sample on how to implement volley in xamarin android Im struggling on GET http request using volley. 

Thank you

**Comment by royd** [comment]
A Xamarin bindings library simply generates Managed Callable Wrappers for an Android library. So usage is the same as normal, unless the members you need are excluded in the Metadata.xml file. [Here](https://developer.android.com/training/volley/simple.html) is a standard example.
